//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagicStaircase.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registros
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public int Puntuacion { get; set; }
        public int Segundos { get; set; }
        public System.DateTime Fecha { get; set; }
        public bool Sistema { get; set; }
    }
}
